export default {
  pages: [
    'pages/index/index',
    'pages/warnup/index',
    'pages/baduanjin/index',
    'pages/inside/index',
    'pages/bafawubu/index',
    'pages/eighteen3/index',

    'pages/eighteen3/byOrder/index',
    'pages/eighteen3/byOrder/baiheliangchi/index',
    'pages/eighteen3/byOrder/danbian/index',
    'pages/eighteen3/byOrder/jingangdaodui2/index',
    'pages/eighteen3/byOrder/jingangdaodui3/index',
    'pages/eighteen3/byOrder/lanzhayi/index',
    'pages/eighteen3/byOrder/liufengsibi/index',
    'pages/eighteen3/byOrder/prepare/index',
    'pages/eighteen3/byOrder/shantongbei/index',
    'pages/eighteen3/byOrder/xiexing2/index',
    'pages/eighteen3/byOrder/zhongpan/index',

    'pages/eighteen3/byAction/index',
    'pages/eighteen3/byAction/baiheliangchi/index',
    'pages/eighteen3/byAction/danbian/index',
    'pages/eighteen3/byAction/jingangdaodui2/index',
    'pages/eighteen3/byAction/jingangdaodui3/index',
    'pages/eighteen3/byAction/lanzhayi/index',
    'pages/eighteen3/byAction/liufengsibi/index',
    'pages/eighteen3/byAction/prepare/index',
    'pages/eighteen3/byAction/shantongbei/index',
    'pages/eighteen3/byAction/xiexing2/index',
    'pages/eighteen3/byAction/zhongpan/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
  cloud: true,
};
