export default {
  pages: [
    'pages/index/index',
    'pages/warnup/index',

    'pages/baduanjin/index',
    'pages/baduanjin/main/index',
    'pages/baduanjin/0104/index',
    'pages/baduanjin/0508/index',

    'pages/inside/index',

    'pages/bafawubu/index',
    'pages/bafawubu/main/index',
    'pages/bafawubu/0117/index',
    'pages/bafawubu/1819/index',
    'pages/bafawubu/2023/index',
    'pages/bafawubu/2425/index',
    'pages/bafawubu/2629/index',
    'pages/bafawubu/3032/index',

    'pages/eighteen3/index',
    'pages/eighteen3/byOrder/index',
    'pages/eighteen3/byOrder/01-prepare/index',
    'pages/eighteen3/byOrder/02-jingangdaodui/index',
    'pages/eighteen3/byOrder/03-lanzhayi/index',
    'pages/eighteen3/byOrder/04-liufengsibi/index',
    'pages/eighteen3/byOrder/05-danbian/index',
    'pages/eighteen3/byOrder/06-jingangdaodui2/index',
    'pages/eighteen3/byOrder/07-10-baiheliangchi/index',
    'pages/eighteen3/byOrder/11-15-xiexing2/index',
    'pages/eighteen3/byOrder/16-jingangdaodui3/index',
    'pages/eighteen3/byOrder/17-18-bishenchui/index',
    'pages/eighteen3/byOrder/19-21-shuangtuizhang/index',
    'pages/eighteen3/byOrder/22-23-daojuangong/index',
    'pages/eighteen3/byOrder/24-zhongpan/index',
    'pages/eighteen3/byOrder/25-baiheliangchi/index',
    'pages/eighteen3/byOrder/26-xiexingaobu/index',
    'pages/eighteen3/byOrder/27-shantongbei/index',
    'pages/eighteen3/byOrder/28-yanshouhongchui/index',
    'pages/eighteen3/byOrder/29-daliufengsibi/index',
    'pages/eighteen3/byOrder/30-danbian/index',
    'pages/eighteen3/byOrder/31-yunshou/index',
    'pages/eighteen3/byOrder/32-gaotanma/index',
    'pages/eighteen3/byOrder/33-youcajiao/index',
    'pages/eighteen3/byOrder/34-zuocajiao/index',
    'pages/eighteen3/byOrder/35-zuodengjiao/index',
    'pages/eighteen3/byOrder/36-qiantangaobu/index',
    'pages/eighteen3/byOrder/37-jidichui/index',
    'pages/eighteen3/byOrder/38-fanshenerqijiao/index',
    'pages/eighteen3/byOrder/39-huxinchui/index',
    'pages/eighteen3/byOrder/40-xuanfengjiao/index',
    'pages/eighteen3/byOrder/41-youdengjiao/index',
    'pages/eighteen3/byOrder/42-haidifanhua/index',
    'pages/eighteen3/byOrder/43-yanshouhongchui/index',
    'pages/eighteen3/byOrder/44-xiaoqinda/index',
    'pages/eighteen3/byOrder/45-baotoutuishan/index',
    'pages/eighteen3/byOrder/46-sanhuanzhang/index',
    'pages/eighteen3/byOrder/47-liufengsibi/index',
    'pages/eighteen3/byOrder/48-danbian/index',
    'pages/eighteen3/byOrder/49-qianzhaohouzhao/index',
    'pages/eighteen3/byOrder/50-yemafenzong/index',
    'pages/eighteen3/byOrder/51-daliufengsibi/index',
    'pages/eighteen3/byOrder/52-danbian/index',
    'pages/eighteen3/byOrder/53-shuangzhenjiao/index',
    'pages/eighteen3/byOrder/54-yunvchuansuo/index',
    'pages/eighteen3/byOrder/55-lanzhayi/index',
    'pages/eighteen3/byOrder/56-liufengsibi/index',
    'pages/eighteen3/byOrder/57-danbian/index',
    'pages/eighteen3/byOrder/58-yunshou/index',
    'pages/eighteen3/byOrder/59-shuangbailian/index',
    'pages/eighteen3/byOrder/60-diecha/index',
    'pages/eighteen3/byOrder/61-jinjiduli/index',
    'pages/eighteen3/byOrder/62-63-daojuangong/index',
    'pages/eighteen3/byOrder/64-zhongpan/index',
    'pages/eighteen3/byOrder/65-baiheliangchi/index',
    'pages/eighteen3/byOrder/66-xiexing/index',
    'pages/eighteen3/byOrder/67-shantongbei/index',
    'pages/eighteen3/byOrder/68-yanshouhongchui/index',
    'pages/eighteen3/byOrder/69-liufengsibi/index',
    'pages/eighteen3/byOrder/70-danbian/index',
    'pages/eighteen3/byOrder/71-yunshou/index',
    'pages/eighteen3/byOrder/72-gaotanma/index',
    'pages/eighteen3/byOrder/73-danbailian/index',
    'pages/eighteen3/byOrder/74-zhidangchui/index',
    'pages/eighteen3/byOrder/75-baiyuanxianguo/index',
    'pages/eighteen3/byOrder/76-liufengsibi/index',
    'pages/eighteen3/byOrder/77-danbian/index',
    'pages/eighteen3/byOrder/78-quedilong/index',
    'pages/eighteen3/byOrder/79-shangbuqixing/index',
    'pages/eighteen3/byOrder/80-tuibukuahu/index',
    'pages/eighteen3/byOrder/81-shuangbailian/index',
    'pages/eighteen3/byOrder/82-dangtoupao/index',
    'pages/eighteen3/byOrder/83-jingangdaodui/index',

    'pages/eighteen3/byAction/index',
    'pages/eighteen3/byAction/baiheliangchi/index',
    'pages/eighteen3/byAction/danbian/index',
    'pages/eighteen3/byAction/jingangdaodui/index',
    'pages/eighteen3/byAction/jingangdaodui2/index',
    'pages/eighteen3/byAction/jingangdaodui3/index',
    'pages/eighteen3/byAction/lanzhayi/index',
    'pages/eighteen3/byAction/liufengsibi/index',
    'pages/eighteen3/byAction/prepare/index',
    'pages/eighteen3/byAction/shantongbei/index',
    'pages/eighteen3/byAction/xiexing2/index',
    'pages/eighteen3/byAction/zhongpan/index',
    'pages/eighteen3/byAction/bishenchui/index',
    'pages/eighteen3/byAction/shuangtuizhang/index',
    'pages/eighteen3/byAction/daojuangong/index',

    'pages/aboutme/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
  cloud: true,
};
