export default {
  pages: [
    'pages/index/index',
    'pages/warnup/index',

    'pages/baduanjin/index',
    'pages/baduanjin/main/index',
    'pages/baduanjin/0104/index',
    'pages/baduanjin/0508/index',

    'pages/inside/index',

    'pages/bafawubu/index',
    'pages/bafawubu/main/index',
    'pages/bafawubu/0117/index',
    'pages/bafawubu/1819/index',
    'pages/bafawubu/2023/index',
    'pages/bafawubu/2425/index',
    'pages/bafawubu/2629/index',
    'pages/bafawubu/3032/index',

    'pages/eighteen3/index',
    'pages/eighteen3/byOrder/index',
    'pages/eighteen3/byOrder/01-prepare/index',
    'pages/eighteen3/byOrder/02-jingangdaodui/index',
    'pages/eighteen3/byOrder/03-lanzhayi/index',
    'pages/eighteen3/byOrder/04-liufengsibi/index',
    'pages/eighteen3/byOrder/05-danbian/index',
    'pages/eighteen3/byOrder/06-jingangdaodui2/index',
    'pages/eighteen3/byOrder/07-10-baiheliangchi/index',
    'pages/eighteen3/byOrder/11-15-xiexing2/index',
    'pages/eighteen3/byOrder/16-jingangdaodui3/index',
    'pages/eighteen3/byOrder/17-18-bishenchui/index',
    'pages/eighteen3/byOrder/19-21-shuangtuizhang/index',
    'pages/eighteen3/byOrder/22-23-daojuangong/index',
    'pages/eighteen3/byOrder/24-zhongpan/index',
    'pages/eighteen3/byOrder/25-26-baiheliangchi2/index',
    'pages/eighteen3/byOrder/27-shantongbei/index',
    'pages/eighteen3/byOrder/28-30-yanshouhongchui/index',
    'pages/eighteen3/byOrder/31-32-yunshou/index',
    'pages/eighteen3/byOrder/33-35-youcajiao/index',
    'pages/eighteen3/byOrder/36-38-qiantangaobu/index',
    'pages/eighteen3/byOrder/39-40-huxinchui/index',
    'pages/eighteen3/byOrder/41-43-youdengjiao/index',
    'pages/eighteen3/byOrder/44-xiaoqinda/index',
    'pages/eighteen3/byOrder/45-48-baotoutuishan/index',
    'pages/eighteen3/byOrder/49-52-qianzhaohouzhao/index',
    'pages/eighteen3/byOrder/53-57-shuangzhenjiao/index',
    'pages/eighteen3/byOrder/58-60-yunshou/index',
    'pages/eighteen3/byOrder/61-jinjiduli/index',
    'pages/eighteen3/byOrder/62-63-daojuangong/index',
    'pages/eighteen3/byOrder/64-zhongpan/index',
    'pages/eighteen3/byOrder/65-66-baiheliangchi2/index',
    'pages/eighteen3/byOrder/67-shantongbei/index',
    'pages/eighteen3/byOrder/68-70-yanshouhongchui/index',
    'pages/eighteen3/byOrder/71-72-yunshou/index',
    'pages/eighteen3/byOrder/73-77-shizidanbailian/index',
    'pages/eighteen3/byOrder/78-81-quedilong/index',
    'pages/eighteen3/byOrder/82-83-dangtoupao/index',

    'pages/eighteen3/byAction/index',
    'pages/eighteen3/byAction/baiheliangchi/index',
    'pages/eighteen3/byAction/danbian/index',
    'pages/eighteen3/byAction/jingangdaodui/index',
    'pages/eighteen3/byAction/jingangdaodui2/index',
    'pages/eighteen3/byAction/jingangdaodui3/index',
    'pages/eighteen3/byAction/lanzhayi/index',
    'pages/eighteen3/byAction/liufengsibi/index',
    'pages/eighteen3/byAction/prepare/index',
    'pages/eighteen3/byAction/shantongbei/index',
    'pages/eighteen3/byAction/xiexing2/index',
    'pages/eighteen3/byAction/zhongpan/index',
    'pages/eighteen3/byAction/bishenchui/index',
    'pages/eighteen3/byAction/shuangtuizhang/index',
    'pages/eighteen3/byAction/daojuangong/index',

    'pages/aboutme/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
  cloud: true,
};
